version: '3.8'

services:
  rag-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: rag-service:1.0
    container_name: rag-service
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./pdf:/app/pdf
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
