# API 配置 - 使用本地 qwen-embedding 模型
API_URL = "http://10.1.141.33:8020/v1/embeddings"
MODEL_NAME = "qwen-embedding"
EMBEDDING_DIM = 1024

# Elasticsearch 配置
ELASTICSEARCH_HOST = "http://10.1.140.215:12300"
ELASTICSEARCH_IP = "10.1.140.215"
ELASTICSEARCH_PORT = "12300"
ELASTICSEARCH_USER = "elastic"
ELASTICSEARCH_PASSWORD = "123456"
ELASTICSEARCH_INDEX = "page_index"
ELASTICSEARCH_SUMMARY_INDEX = "doc_summary_index"

# API 配置
API_KEY=""

DEEPSEEK_API_URL="https://api.deepseek.com/v1/chat/completions"
DEEPSEEK_V3_MODEL_NAME="deepseek-chat"

# 搜索配置
DEFAULT_SEARCH_MODE="smart"
DEFAULT_DOC_TYPE="不指定类型"
DEFAULT_MODEL_NAME="deepseek-chat"
DEFAULT_LIMIT_VECTOR="10"
DEFAULT_LIMIT_JSON="10"

# 数据库配置
POSTGRES_IP = "10.1.140.215"
POSTGRES_POST = "5435"
POSTGRES_USER = "root"
POSTGRES_PASSWORD = "123456"
POSTGRES_DB = "deepsearch"

DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_IP}:{POSTGRES_POST}/{POSTGRES_DB}"

# MinIO配置
MINIO_IP = "10.1.140.215"
MINIO_PORT = "19300"
MINIO_CONSOLE_PORT = "19301"
MINIO_USER = "deepsearch"
MINIO_PASSWORD = "12345678"

# Redis配置
REDIS_IP = "10.1.140.215"
REDIS_PORT = "16380"
REDIS_PASSWORD = "123456"

# MinIO桶名配置
MINIO_BUCKET_FILES = "files"
MINIO_BUCKET_DOCUMENT = "document"
