# Embedding 配置 - qwen-embedding
API_URL = "http://10.1.141.33:8020/v1/embeddings"
MODEL_NAME = "qwen-embedding"
EMBEDDING_DIM = 1024

# Elasticsearch 配置
ELASTICSEARCH_HOST = "http://10.1.140.215:12300"
ELASTICSEARCH_IP = "10.1.140.215"
ELASTICSEARCH_PORT = "12300"
ELASTICSEARCH_USER = "elastic"
ELASTICSEARCH_PASSWORD = "123456"
ELASTICSEARCH_INDEX = "page_index"
ELASTICSEARCH_SUMMARY_INDEX = "doc_summary_index"
ELASTICSEARCH_DOC_INDEX = "doc_index"
ELASTICSEARCH_CHAPTER_INDEX = "chapter_index"
ELASTICSEARCH_CHUNK_INDEX = "chunk_index"

# API 配置
API_KEY=""

DEEPSEEK_API_URL="https://api.deepseek.com/v1/chat/completions"
DEEPSEEK_V3_MODEL_NAME="deepseek-chat"

# 搜索配置
DEFAULT_SEARCH_MODE="smart"
DEFAULT_DOC_TYPE="不指定类型"
DEFAULT_MODEL_NAME="deepseek-chat"
DEFAULT_LIMIT_VECTOR="10"
DEFAULT_LIMIT_JSON="10"

# 数据库配置
POSTGRES_IP = "10.1.140.215"
POSTGRES_POST = "5435"
POSTGRES_USER = "root"
POSTGRES_PASSWORD = "123456"
POSTGRES_DB = "deepsearch_dev"

DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_IP}:{POSTGRES_POST}/{POSTGRES_DB}"

# MinIO配置
MINIO_IP = "10.1.140.215"
MINIO_PORT = "19300"
MINIO_CONSOLE_PORT = "19301"
MINIO_USER = "deepsearch"
MINIO_PASSWORD = "12345678"

# Redis配置
REDIS_IP = "10.1.140.215"
REDIS_PORT = "16380"
REDIS_PASSWORD = "123456"

# MinIO桶名配置
MINIO_BUCKET_FILES = "files"
MINIO_BUCKET_DOCUMENT = "deepsearch-dev"

# RAG处理配置
RAG_OUTPUT_DIR = "pdf"
RAG_BUCKET_NAME = "deepsearch-dev"
RAG_LLM_URL = "http://10.1.141.33:8080/v1/chat/completions"
RAG_LLM_MODEL = "qwen3.5-35b-int4"
LLM_REQUEST_TIMEOUT = 900
RAG_SHORT_DOC_TOKEN_THRESHOLD = 8000
RAG_PROCESS_BAT_CHAR_CAPACITY = 1000000
RAG_DOC_THREAD_POOL_WORKERS = 8

# Rerank配置
RERANK_URL = "http://10.1.141.33:8474/rerank"
RERANK_TIMEOUT = 30

# 文件转换配置
ONLINE_PREVIEW_BASE_URL = "http://10.1.140.215:8012"
LIBREOFFICE_CONVERT_TIMEOUT = 300
SUPPORTED_CONVERT_EXTENSIONS = {
    ".doc", ".docx",
    ".txt", ".json",
    ".ppt", ".pptx",
    ".xls", ".xlsx",
}

# PDF解析配置
PDF_SIMPLE_LLM_URL = RAG_LLM_URL
PDF_SIMPLE_LLM_MODEL = RAG_LLM_MODEL
PDF_SIMPLE_MODEL = RAG_LLM_MODEL
PDF_IF_THINNING = False
PDF_THINNING_THRESHOLD = 5000
PDF_SUMMARY_TOKEN_THRESHOLD = 200
PDF_IF_SUMMARY = True
PDF_IF_ADD_NODE_TEXT = True

# PDF长文档分块配置
PDF_TOC_SCAN_PAGES = 15
PDF_MAX_TOKENS_PER_CHUNK = 6000
PDF_CHUNK_TOKEN_THRESHOLD = 20000
PDF_PAGES_PER_CHUNK = 10
PDF_MERGE_SMALL_CHUNKS = True
PDF_SMALL_CHUNK_CHAR_THRESHOLD = 100
PDF_ENABLE_SEMANTIC_PARAGRAPH_SPLIT = True
PDF_SEMANTIC_SPLIT_SIMILARITY_THRESHOLD = 0.6
PDF_SEMANTIC_SPLIT_MIN_PARAGRAPH_CHARS = 100
PDF_SEMANTIC_SPLIT_MIN_SEGMENT_CHARS = 80
PDF_SEMANTIC_SPLIT_EMBEDDING_WORKERS = 64
PDF_ENABLE_CLEANING = True
PDF_SUMMARY_CHAR_CAPACITY = 45000
