FROM python:3.10

# 更新系统并安装依赖
RUN apt-get update && apt-get install -y \
    libreoffice \
    fonts-wqy-zenhei \
    fonts-wqy-microhei \
    xfonts-wqy \
    ttf-wqy-microhei \
    ttf-wqy-zenhei \
    language-pack-zh-hans \
    locales \
    curl

# 配置中文语言环境
RUN echo "zh_CN.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen zh_CN.UTF-8 && \
    update-locale LANG=zh_CN.UTF-8

# 设置环境变量
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh
ENV LC_ALL zh_CN.UTF-8